### PR TITLE
Updated README page for better readability

### PR DESCRIPTION
**Pull request by jobyko**

### CODE REVIEW

**Comment by jobyko** [comment]
@sumodgeorge  @asa1997 
Kindly review the changes and share your comments.

**Comment by asa1997** [comment]
@jobyko 
Can you please add asciinema gif to this as well.
@panickervinod

**Comment by jobyko** [comment]
Some network may block asciinema gif. Will be adding short videos instead (later).

**Comment by jobyko** [comment]
+
Added commit contains, images for wiki with this with pull request. 
@asa1997

**Review by asa1997 — APPROVED** [review]
@jobyko @panickervinod LGTM.
If asciinema isnt working try adding a vimeo video as a temporary thing.

**Pull request merged**
