### PR TITLE
Updated help command

### PR DESCRIPTION
**Pull request by pramit-d**
https://github.com/Be-Secure/BeSman/issues/97

Added help command for each BeSman command separately.

list of commands:
- install
- uninstall
- list
- status
- set 
- create
- upgrade
- update
- help
- version
- rm or remove
- run 
- validate
- reset
-pull

Peek 2024-03-27 15-28

### CODE REVIEW

**Review by asa1997 — CHANGES_REQUESTED** [review]
@pramit-d Can you please add more content into this.

**Comment by asa1997** [comment]
Closing as changes required

**Comment by pramit-d** [comment]
@asa1997 Please provide details for BeSman config variables.

Screenshot from 2024-03-27 15-30-56

**Comment by pramit-d** [comment]
Screenshot from 2024-03-27 17-32-29

**Review by asa1997 — CHANGES_REQUESTED** [review]
@pramit-d 
- The detailed help for pull is not working. Please add that as well. 
- Also, please add this feature into the help command usage as well as the readme's usage.
- Also, when a syntax error occurs, please display the detailed help of the respective command.

**Comment by pramit-d** [comment]
> @pramit-d Few changes
> 
> * The detailed help for pull, run is not working. Please add that as well.
> * Please add this feature into the help command usage as well as the readme's usage.
> * When a syntax error occurs, please display the detailed help of the respective command.

@asa1997 Updated.

**Review by asa1997 — APPROVED** [review]
@pramit-d LGTM

**Pull request merged**
